### ISSUE TITLE
After changing date field query gives wrong results

### ISSUE THREAD

**Issue by melvinwevers** [UUDigitalHumanitieslab/texcavator#127]
After changing the date field and pressing enter to search, the result is wrong (too many hits)
They only update after clicking on the search light. This happens both in Safari and Chrome. 

This is probably linked to the other interface problems, but nevertheless, I thought I should report this.

**Comment by jgonggrijp** [comment]
Could you provide a particular example where this behaviour occurs? I haven't been able to observe this myself, yet.

**Comment by melvinwevers** [comment]
Search for all articles using * between 01-01-1917 and 31-12-1917. Then changed the date to 01-01-198 and 31-12-1918. If you push enter the search is not correct, and if you push the search lantern, you sometimes have to click twice. It seems that it first finds the results from 1917 & 1918. Only after clicking twice it looks within 1918 only.

**Comment by jgonggrijp** [comment]
I'm a bit surprised that you are able to search for just `*` at all—this is unsupported. I'm going to look into that next.

Anyway, even if I retry your exact example, I do not see the behaviour that you describe. When I search for `*` within 1917 (by pressing enter while in the text box), I get 807575 results. If I then change the date range to 1918, put the caret back in the text box and press enter again, I always get 752413 results. The same happens if I leave the caret in one of the date fields. Does the procedure that you follow differ in any way from what I just described?

Does the same effect also occur with a different query string?

**Comment by melvinwevers** [comment]
Well searching for * is somewhat necessary when determining the number of articles in one year (or period).

I'll test the behavior later today

**Comment by melvinwevers** [comment]
It occurs when you select for select for regional and national newspaper articles + advertisements. Perhaps the metadata filters do not instantly apply, but only after clicking twice?

**Comment by jgonggrijp** [comment]
As it turns out, the Dojo `DateTextBox` widget only updates when you pick a date with the calendar picker. There is a switch that causes it to also update when you change the date using the keyboard, but it is off by default. Finding that took some time, but I think I fixed it.

**Comment by melvinwevers** [comment]
Has milestone 9 been released? This bug is still present in the current version..

**Comment by mhkuu** [comment]
Nope, we probably should release the milestone ASAP (i.e. next week). I wanted to resolve #112 before releasing, but that turns out to be even more weird than this thing.

**Comment by mhkuu** [comment]
@melvinwevers I released Milestone 9 yesterday! :-)

**Comment by melvinwevers** [comment]
😃👍
